# Generated by Django 4.1.6 on 2023-02-15 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='average_heartrate',
            field=models.IntegerField(default=-1),
        ),
    ]
